# Generated by Django 5.0.6 on 2025-12-17 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_sensorprediction_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_sign', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('grayscale_image', models.ImageField(blank=True, null=True, upload_to='traffic_signs/grayscale/')),
                ('blurred_image', models.ImageField(blank=True, null=True, upload_to='traffic_signs/blurred/')),
                ('equalized_image', models.ImageField(blank=True, null=True, upload_to='traffic_signs/equalized/')),
                ('thresholded_image', models.ImageField(blank=True, null=True, upload_to='traffic_signs/thresholded/')),
                ('roi_image', models.ImageField(blank=True, null=True, upload_to='traffic_signs/roi/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='traffic_signs/original/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SensorPrediction',
        ),
        migrations.AddField(
            model_name='signprediction',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='myapp.signupload'),
        ),
    ]
